CREATE TABLE `hosafot_readings` (
	`id` integer PRIMARY KEY NOT NULL,
	`sefer` text NOT NULL,
	`parsha_id_1` integer,
	`parsha_id_2` integer,
	`occasion_id` integer,
	`is_double_parsha` integer DEFAULT 0 NOT NULL,
	`chapter_start` integer NOT NULL,
	`verse_start` integer NOT NULL,
	`chapter_end` integer NOT NULL,
	`verse_end` integer NOT NULL,
	`pseukim` integer NOT NULL,
	`date_read` text NOT NULL,
	`note` text,
	`location` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`parsha_id_1`) REFERENCES `parshiot`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`parsha_id_2`) REFERENCES `parshiot`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`occasion_id`) REFERENCES `occasions`(`id`) ON UPDATE no action ON DELETE no action
);
