// Generates src/db/nativeMigrations.generated.ts from the drizzle SQL migrations, for
// @capacitor-community/sqlite's addUpgradeStatement()/createConnection() version-upgrade
// mechanism used by src/db/native.ts. See CLAUDE.md's "Native (Capacitor) migrations" section
// for how this fits together.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readMigrationSteps } from '../src/utils/migrationSteps.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DRIZZLE_DIR = path.join(__dirname, '../drizzle');
const OUT_FILE = path.join(__dirname, '../src/db/nativeMigrations.generated.ts');

// The same steps the server's runner applies (src/utils/migrationSteps.ts).
const upgradeSteps = readMigrationSteps(DRIZZLE_DIR);

const NATIVE_DB_VERSION = upgradeSteps.length;

const banner = '// AUTO-GENERATED by scripts/build-native-migrations.ts — do not edit by hand.\n';
const body = `import type { capSQLiteVersionUpgrade } from '@capacitor-community/sqlite';

export const NATIVE_DB_VERSION = ${NATIVE_DB_VERSION};

export const NATIVE_UPGRADE_STATEMENTS: capSQLiteVersionUpgrade[] = ${JSON.stringify(upgradeSteps, null, 2)};
`;

fs.writeFileSync(OUT_FILE, banner + body);
console.log(`Wrote ${path.relative(process.cwd(), OUT_FILE)} (NATIVE_DB_VERSION=${NATIVE_DB_VERSION})`);
