// Generates src/db/nativeMigrations.generated.ts from the drizzle SQL migrations, for
// @capacitor-community/sqlite's addUpgradeStatement()/createConnection() version-upgrade
// mechanism used by src/db/native.ts. See CLAUDE.md's "Native (Capacitor) migrations" section
// for how this fits together.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DRIZZLE_DIR = path.join(__dirname, '../drizzle');
const OUT_FILE = path.join(__dirname, '../src/db/nativeMigrations.generated.ts');

interface JournalEntry {
  idx: number;
  tag: string;
}

const journal: { entries: JournalEntry[] } = JSON.parse(
  fs.readFileSync(path.join(DRIZZLE_DIR, 'meta/_journal.json'), 'utf8')
);

const entries = [...journal.entries].sort((a, b) => a.idx - b.idx);

function splitStatements(sql: string): string[] {
  return sql
    .split('--> statement-breakpoint')
    .map(chunk => chunk.trim())
    .filter(chunk => chunk.length > 0);
}

const upgradeSteps = entries.map((entry, i) => ({
  toVersion: i + 1,
  statements: splitStatements(fs.readFileSync(path.join(DRIZZLE_DIR, `${entry.tag}.sql`), 'utf8')),
}));

const NATIVE_DB_VERSION = upgradeSteps.at(-1)!.toVersion;

const banner = '// AUTO-GENERATED by scripts/build-native-migrations.ts — do not edit by hand.\n';
const body = `import type { capSQLiteVersionUpgrade } from '@capacitor-community/sqlite';

export const NATIVE_DB_VERSION = ${NATIVE_DB_VERSION};

export const NATIVE_UPGRADE_STATEMENTS: capSQLiteVersionUpgrade[] = ${JSON.stringify(upgradeSteps, null, 2)};
`;

fs.writeFileSync(OUT_FILE, banner + body);
console.log(`Wrote ${path.relative(process.cwd(), OUT_FILE)} (NATIVE_DB_VERSION=${NATIVE_DB_VERSION})`);
