/**
 * Convert a DB built by the OLD migration chain (drizzle 0000–0010 + the
 * pre-drizzle `schema_migrations` runner) to the NEW two-migration pattern
 * (0000_baseline + 0001_seed), preserving all user data.
 *
 * Old DBs cannot simply be re-migrated: drizzle applies any journal entry newer
 * than the newest row in `__drizzle_migrations`, so the squashed baseline would
 * re-run against tables that already exist and fail. Rather than patch the old
 * schema in place, this builds a pristine DB from drizzle/ and copies the
 * non-seed rows into it, so the resulting structure is exactly what the
 * committed migrations produce.
 *
 * Seed tables (anything 0001_seed.sql inserts into) are NOT copied — they are
 * regenerated by the migration. They are compared first instead: user rows
 * reference seed ids, so the copy is only safe if those ids are identical on
 * both sides.
 *
 *   npx tsx scripts/db-migrate-user-data.ts --dry-run
 *   npx tsx scripts/db-migrate-user-data.ts torah.db
 *   npx tsx scripts/db-migrate-user-data.ts torah.db --out converted.db
 */
import fs                 from 'node:fs';
import path               from 'node:path';
import crypto             from 'node:crypto';
import { parseArgs }      from 'node:util';
import { fileURLToPath }  from 'node:url';
import Database           from 'better-sqlite3';
import { createDb }       from '../src/db/drizzle-server.js';
import { initDb }         from '../src/db/init.js';

type Db = InstanceType<typeof Database>;

const __dirname       = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR  = path.join(__dirname, '../drizzle');
const SEED_MIGRATION  = '0001_seed.sql';

/** Legacy ledger from the pre-drizzle migration runner; dropped by the rebuild. */
const LEGACY_TABLES   = ['schema_migrations'];

const { values: flags, positionals } = parseArgs({
  allowPositionals: true,
  options: {
    out:         { type: 'string'  },                  // write here instead of replacing the source
    'dry-run':   { type: 'boolean', default: false },
    'no-backup': { type: 'boolean', default: false },
    force:       { type: 'boolean', default: false },  // proceed despite seed drift
  },
});

const sourcePath = path.resolve(positionals[0] ?? process.env.TORAH_DB_PATH ?? path.join(__dirname, '../torah.db'));
const outPath    = flags.out ? path.resolve(flags.out) : sourcePath;
const dryRun     = flags['dry-run'];

// ---------------------------------------------------------------- helpers

/** Tables the seed migration populates — regenerated, never copied. */
function seedTables(migrationsDir: string): Set<string> {
  const sql     = fs.readFileSync(path.join(migrationsDir, SEED_MIGRATION), 'utf8');
  const matches = sql.matchAll(/INSERT\s+(?:OR\s+\w+\s+)?INTO\s+[`"]?(\w+)[`"]?/gi);
  return new Set([...matches].map(m => m[1].toLowerCase()));
}

function userTables(db: Db): string[] {
  return db.prepare(`
    SELECT name FROM sqlite_master
     WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name != '__drizzle_migrations'
     ORDER BY name
  `).pluck().all() as string[];
}

function columnsOf(db: Db, table: string): string[] {
  return db.prepare(`PRAGMA table_info("${table}")`).all().map((c: any) => c.name);
}

/** `a, b` → `"a","b"` — identifier list safe to drop into a SELECT/INSERT. */
function quoteList(columns: string[]): string {
  return columns.map(c => `"${c}"`).join(',');
}

function rowCount(db: Db, table: string): number {
  return db.prepare(`SELECT COUNT(*) FROM "${table}"`).pluck().get() as number;
}

/**
 * Content fingerprint of a table, independent of insertion order: rows are
 * sorted by every column so two DBs that hold the same data hash the same.
 */
function contentHash(db: Db, table: string): string {
  const cols  = columnsOf(db, table);
  const order = cols.map((_, i) => i + 1).join(',');
  const rows  = db.prepare(`SELECT ${quoteList(cols)} FROM "${table}" ORDER BY ${order}`).raw().all();
  return crypto.createHash('sha256').update(JSON.stringify(rows)).digest('hex').slice(0, 16);
}

/** Hash each migration file the way drizzle's migrator does, to check the ledger. */
function expectedLedger(migrationsDir: string): { hash: string; createdAt: number }[] {
  const journal = JSON.parse(fs.readFileSync(path.join(migrationsDir, 'meta/_journal.json'), 'utf8'));
  return journal.entries.map((entry: { tag: string; when: number }) => ({
    hash:      crypto.createHash('sha256').update(fs.readFileSync(path.join(migrationsDir, `${entry.tag}.sql`)).toString()).digest('hex'),
    createdAt: entry.when,
  }));
}

function buildFreshDb(dbPath: string): void {
  const raw = new Database(dbPath);
  raw.pragma('journal_mode = DELETE');
  raw.pragma('foreign_keys = OFF'); // must be off during migrations (table recreations need it)
  initDb(raw, createDb(raw), MIGRATIONS_DIR);
  raw.close();
}

function fail(message: string): never {
  console.error(`\n✗ ${message}`);
  process.exit(1);
}

// ---------------------------------------------------------------- main

if (!fs.existsSync(sourcePath)) fail(`No such database: ${sourcePath}`);

console.log(`source: ${sourcePath}`);
console.log(`target: ${outPath}${dryRun ? ' (dry run — nothing will be written)' : ''}\n`);

const tempPath = `${outPath}.converting-${process.pid}`;
fs.rmSync(tempPath, { force: true });
buildFreshDb(tempPath);

const source = new Database(sourcePath, { readonly: true });
const fresh  = new Database(tempPath);
fresh.pragma('foreign_keys = ON'); // copied rows must resolve against the regenerated seed

try {
  const seeded    = seedTables(MIGRATIONS_DIR);
  const inFresh   = userTables(fresh);
  const inSource  = new Set(userTables(source));
  const toCopy    = inFresh.filter(t => !seeded.has(t));
  const toCompare = inFresh.filter(t =>  seeded.has(t));

  console.log(`seed tables (regenerated from ${SEED_MIGRATION}): ${toCompare.join(', ')}`);
  console.log(`user tables (copied from source):                 ${toCopy.join(', ')}\n`);

  // --- preflight: seed data must be identical, or copied foreign keys may point elsewhere
  let drift = 0;
  for (const table of toCompare) {
    if (!inSource.has(table)) {
      console.log(`  ${table.padEnd(18)} absent in source — will be seeded fresh`);
      continue;
    }
    const oldHash = contentHash(source, table);
    const newHash = contentHash(fresh,  table);
    if (oldHash === newHash) continue;
    drift++;
    console.log(`  ${table.padEnd(18)} SEED DRIFT  source=${oldHash} (${rowCount(source, table)} rows)  baseline=${newHash} (${rowCount(fresh, table)} rows)`);
  }
  if (drift > 0 && !flags.force) {
    fail(`${drift} seed table(s) differ from the baseline. User rows reference these ids, so copying could\n`
       + `  attach readings to the wrong aliyot. Inspect the differences, then re-run with --force to accept.`);
  }
  if (drift === 0) console.log('  seed data identical to the baseline — foreign keys will resolve unchanged\n');

  const legacyFound = LEGACY_TABLES.filter(t => inSource.has(t));
  if (legacyFound.length) console.log(`dropping legacy migration table(s): ${legacyFound.join(', ')}\n`);

  // --- copy user rows
  fresh.exec(`ATTACH DATABASE '${sourcePath.replaceAll("'", "''")}' AS src`);
  const copy = fresh.transaction(() => {
    for (const table of toCopy) {
      if (!inSource.has(table)) {
        console.log(`  ${table.padEnd(18)} absent in source — 0 rows`);
        continue;
      }
      const sourceCols = columnsOf(source, table);
      const freshCols  = columnsOf(fresh,  table);
      const shared     = freshCols.filter(c => sourceCols.includes(c));
      const dropped    = sourceCols.filter(c => !freshCols.includes(c));
      const added      = freshCols.filter(c => !sourceCols.includes(c));

      const list    = quoteList(shared);
      const changes = fresh.prepare(`INSERT INTO main."${table}" (${list}) SELECT ${list} FROM src."${table}"`).run().changes;

      let note = '';
      if (dropped.length) note += `  (source-only columns discarded: ${dropped.join(', ')})`;
      if (added.length)   note += `  (new columns defaulted: ${added.join(', ')})`;
      console.log(`  ${table.padEnd(18)} ${String(changes).padStart(6)} rows copied${note}`);
    }
  });

  if (dryRun) {
    console.log('\nwould copy:');
    for (const table of toCopy) console.log(`  ${table.padEnd(18)} ${String(inSource.has(table) ? rowCount(source, table) : 0).padStart(6)} rows`);
    console.log('\n✓ dry run complete — no files changed');
  } else {
    console.log('copying user data:');
    copy();
  }

  // --- verify
  for (const table of toCopy) {
    if (!inSource.has(table) || dryRun) continue;
    const expected = rowCount(source, table);
    const actual   = rowCount(fresh,  table);
    if (expected !== actual) fail(`${table}: copied ${actual} rows but source has ${expected}`);
  }
  fresh.exec('DETACH DATABASE src');

  if (!dryRun) {
    const violations = fresh.pragma('foreign_key_check') as unknown[];
    if (violations.length) fail(`foreign key violations after copy: ${JSON.stringify(violations.slice(0, 5))}`);

    const integrity = (fresh.pragma('integrity_check') as { integrity_check: string }[])[0].integrity_check;
    if (integrity !== 'ok') fail(`integrity check failed: ${integrity}`);

    const ledger   = fresh.prepare('SELECT hash, created_at FROM __drizzle_migrations ORDER BY created_at').all() as { hash: string; created_at: number }[];
    const expected = expectedLedger(MIGRATIONS_DIR);
    const ledgerOk = ledger.length === expected.length
      && ledger.every((row, i) => row.hash === expected[i].hash && Number(row.created_at) === expected[i].createdAt);
    if (!ledgerOk) fail(`migration ledger does not match drizzle/meta/_journal.json (${ledger.length} rows, expected ${expected.length})`);

    console.log(`\nverified: ${expected.length} migrations recorded, foreign keys resolve, integrity ok`);
  }
} finally {
  source.close();
  fresh.close();
}

if (dryRun) {
  fs.rmSync(tempPath, { force: true });
  process.exit(0);
}

// --- re-running the migrator must be a no-op: proof the DB is on the new chain
buildFreshDb(tempPath);
const check  = new Database(tempPath, { readonly: true });
const stamps = check.prepare('SELECT COUNT(*) FROM __drizzle_migrations').pluck().get() as number;
check.close();
if (stamps !== expectedLedger(MIGRATIONS_DIR).length) fail(`re-running the migrator changed the ledger (${stamps} rows) — conversion is not stable`);
console.log('verified: re-running the migrator is a no-op');

// --- swap into place
if (!flags['no-backup'] && fs.existsSync(outPath)) {
  const stamp  = new Date().toISOString().replaceAll(/[:.]/g, '-');
  const backup = `${outPath}.bak-${stamp}`;
  fs.copyFileSync(outPath, backup);
  console.log(`\nbackup: ${backup}`);
}
fs.renameSync(tempPath, outPath);
console.log(`✓ converted ${outPath} to the squashed baseline`);
